# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.omnibus.chef_version = :latest

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1", "--ioapic", "on"]
  end

$script = <<SCRIPT
  echo "nameserver 8.8.8.8" > /etc/resolv.conf
  echo "PEERDNS=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
SCRIPT

  config.vm.define :monitor do |monitor|
    monitor.vm.box = "centos-6.5-x86_64"
    monitor.vm.network :private_network, ip: "10.0.0.3"
    monitor.vm.hostname = "zbx01"
    monitor.ssh.guest_port = 62323
    monitor.vm.network :forwarded_port, guest: 62323, host: 2222, id: "ssh", auto_correct: true
    monitor.vm.provision "shell", inline: $script
    monitor.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../chef/site-cookbooks/"
      chef.run_list = %w[
        recipe[base]
        recipe[ntp]
        recipe[postfix]
        recipe[apache2]
        recipe[php]
        recipe[mysql::client]
        recipe[mysql::server]
        recipe[mysql::setup]
        recipe[mysql::conf]
        recipe[zabbix-server]
        recipe[mysql::zabbix]
        recipe[apache2::zabbix]
      ]
    end
  end
end
